### ISSUE TITLE
This release includes the com.google.android.gms.permission.AD_ID - Question / bug

### ISSUE THREAD

**Issue by avrim-tr** [MaximBelov/cordova-plugin-fbsdk#11]
Hey,

When I try to deploy a version in Android to Google play, I get an error:
This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.

I thought that doing this:
```
<plugin name="cordova-plugin-fbsdk" spec="4.0.2">
    <variable name="APP_ID" value="*****"/>
    <variable name="APP_NAME" value="****"/>
    <variable name="CLIENT_TOKEN" value="****" />
    **<variable name="FACEBOOK_ADVERTISER_ID_COLLECTION" value="false" />**
  </plugin>
```
Note the bold, this isI thought to do as written in doc, but it dose not work: 
    <variable name="FACEBOOK_ADVERTISER_ID_COLLECTION" value="false" />

Any suggestion please?

**Bug or feature request**

[X] I'm reporting a reproducible issue with the code

**Comment by MaximBelov** [comment]
Follow instruction
https://stackoverflow.com/questions/71473553/action-requested-declare-your-ad-id-permission
