### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FBSDKCoreKit":   In Podfile:     FBSDKCoreKit (= 17.0.0)

### ISSUE THREAD

**Issue by codeconsole** [MaximBelov/cordova-plugin-fbsdk#12]
```
npx cordova plugin add cordova-plugin-fbsdk --save --variable APP_ID=...--variable APP_NAME=...--variable CLIENT_TOKEN="...."
```

```
CocoaPods could not find compatible versions for pod "FBSDKCoreKit":   In Podfile:     FBSDKCoreKit (= 17.0.0)  Specs satisfying the `FBSDKCoreKit (= 17.0.0)` dependency were found, but they required a higher minimum deployment target.
```

```
% npx cordova -v
12.0.0 (cordova-lib@12.0.1)

% npx cordova platform ls
Installed platforms:
  android 13.0.0
  browser 7.0.0
  ios 7.1.0
```

```
% npx cordova plugin ls
@havesource/cordova-plugin-push 4.0.0 "Cordova Push Plugin"
cordova-launch-review 4.1.0 "Launch Review"
cordova-plugin-app-version 0.1.14 "AppVersion"
cordova-plugin-camera 7.0.0 "Camera"
cordova-plugin-device 2.1.0 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-fbsdk 4.1.0 "Facebook Connect"
cordova-plugin-file 8.1.0 "File"
cordova-plugin-firebase-analytics 8.0.0 "FirebaseAnalyticsPlugin"
cordova-plugin-geolocation 5.0.0 "Geolocation"
cordova-plugin-inappbrowser 6.0.0 "InAppBrowser"
cordova-plugin-purchase 13.11.1 "Purchase"
cordova-plugin-screen-orientation 3.0.4 "Screen Orientation"
cordova-plugin-sign-in-with-apple 0.1.2 "cordova-plugin-sign-in-with-apple"
cordova-plugin-statusbar 4.0.0 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-support-android-plugin 2.0.4 "cordova-support-android-plugin"
es6-promise-plugin 4.2.2 "Promise"
```

**Comment by codeconsole** [comment]
Seems similar to this
https://github.com/capacitor-community/facebook-login/issues/35

**Comment by codeconsole** [comment]
tried
```
% pod repo update

Updating spec repo `trunk`


% pod install --repo-update

Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    FBSDKCoreKit (= 17.0.0)

Specs satisfying the `FBSDKCoreKit (= 17.0.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by codeconsole** [comment]
This is due to the Podfile being 11.0
```
% cat Podfile

# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!

...
```

but any time I update it to 12, it goes back to 11.

**Comment by codeconsole** [comment]
https://stackoverflow.com/questions/36768548/cordova-ios-how-to-change-minimum-deployment-version

Probably should update [README.md](https://github.com/MaximBelov/cordova-plugin-fbsdk/blob/master/docs/ios/README.md) or [TROUBLESHOOTING.md](https://github.com/MaximBelov/cordova-plugin-fbsdk/blob/master/docs/TROUBLESHOOTING.md#ios)

or update [plugin.xml](https://github.com/MaximBelov/cordova-plugin-fbsdk/blob/master/plugin.xml)

**Comment by MaximBelov** [comment]
@codeconsole Thank you for report

Please try cordova-plugin-fbsdk@4.1.1

Demo project with latest changes
`npm run build:ios`
https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect-lab/commit/e02b073807f0d04ca2184cf4f486ab9e8086f9bd

**Comment by sevkonline** [comment]
I added the latest version to my project, but this problem persists.

**Comment by MaximBelov** [comment]
Please provide your plugin list

**Comment by sevkonline** [comment]
`% npx cordova -v
12.0.0 (cordova-lib@12.0.1)

% npx cordova platform ls
Installed platforms:
  android 13.0.0
  browser 7.0.0
  ios 7.1.0`

`admob-plus-cordova 1.29.0 "admob-plus-cordova"
cordova-clipboard 1.3.0 "Clipboard"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-apprate 1.7.2 "AppRate"
cordova-plugin-device 2.1.0 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-facebook-connect 3.2.1 "Facebook Connect"
cordova-plugin-file-opener2 4.0.0 "File Opener2"
cordova-plugin-file 8.0.1 "File"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.8 "cordova-plugin-filepath"
cordova-plugin-firebase-crashlytics 1.2.0 "Cordova Firebase Crashlytics Plugin"
cordova-plugin-googleplus 8.5.2 "Google SignIn"
cordova-plugin-idfa 3.0.0 "cordova-plugin-idfa"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-purchase 13.10.0 "Purchase"
cordova-plugin-resource-generator 0.1.0 "Appery.io Resource Generator"
cordova-plugin-secure-storage-echo 5.1.1 "SecureStorage"
cordova-plugin-sign-in-with-apple 0.1.2 "cordova-plugin-sign-in-with-apple"
cordova-plugin-splashscreen 6.0.1 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-x-socialsharing 6.0.4 "SocialSharing"
cordova-sqlite-ext 6.0.0 "Cordova sqlite storage plugin - (...) with extra features"
cordova.plugins.diagnostic 6.1.0 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.22 "Ionic Deeplink Plugin"
phonegap-plugin-barcodescanner 8.1.1 "BarcodeScanner"
phonegap-plugin-push 2.3.2 "PushPlugin"`

**Comment by sevkonline** [comment]
`% npx cordova -v
12.0.0 (cordova-lib@12.0.1)

% npx cordova platform ls
Installed platforms:
  android 13.0.0
  browser 7.0.0
  ios 7.1.0`

```c
admob-plus-cordova 1.29.0 "admob-plus-cordova"
cordova-clipboard 1.3.0 "Clipboard"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-apprate 1.7.2 "AppRate"
cordova-plugin-device 2.1.0 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-facebook-connect 3.2.1 "Facebook Connect"
cordova-plugin-file-opener2 4.0.0 "File Opener2"
cordova-plugin-file 8.0.1 "File"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.8 "cordova-plugin-filepath"
cordova-plugin-firebase-crashlytics 1.2.0 "Cordova Firebase Crashlytics Plugin"
cordova-plugin-googleplus 8.5.2 "Google SignIn"
cordova-plugin-idfa 3.0.0 "cordova-plugin-idfa"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-purchase 13.10.0 "Purchase"
cordova-plugin-resource-generator 0.1.0 "Appery.io Resource Generator"
cordova-plugin-secure-storage-echo 5.1.1 "SecureStorage"
cordova-plugin-sign-in-with-apple 0.1.2 "cordova-plugin-sign-in-with-apple"
cordova-plugin-splashscreen 6.0.1 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-x-socialsharing 6.0.4 "SocialSharing"
cordova-sqlite-ext 6.0.0 "Cordova sqlite storage plugin - (...) with extra features"
cordova.plugins.diagnostic 6.1.0 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.22 "Ionic Deeplink Plugin"
phonegap-plugin-barcodescanner 8.1.1 "BarcodeScanner"
phonegap-plugin-push 2.3.2 "PushPlugin"
```

**Comment by MaximBelov** [comment]
Please try the demo project to reproduce with your plugins

I removed some plugins because I don't have a configuration

1 Step: try `npm run build:ios` 
2 Step: try to add removed plugins (one by one )
see
https://github.com/MaximBelov/cordova-plugin-fbsdk-lab/commit/42a31ab26930f3ab00c662f53d2ac0d94b6db716

**Comment by Afnan0711** [comment]
Hi guys... i am facing the same issue.. any working solution?

**Comment by MaximBelov** [comment]
Hi @Afnan0711 
Please use the demo repository to reproduce
https://github.com/MaximBelov/cordova-plugin-fbsdk-lab/blob/master/package.json

How to reproduce 
1 Clone repo
2 npm i
3 npm run build:ios
4 Add one of your plugins -> ionic cordova plugin add...
5 npm run build:ios

Using this instruction you can find the plugin that is causing the error.

**Comment by MaximBelov** [comment]
@Afnan0711 
Keep in mind
Do not install plugin "cordova-plugin-facebook-connect"
Please use "cordova-plugin-fbsdk" 4.1.1
