### ISSUE TITLE
Error to run this plugin

### ISSUE THREAD

**Issue by luispimenta** [MaximBelov/cordova-plugin-fbsdk#16]
Hi, I installed this plugin but when I run it on iOS I get the following error:

WARN: Install the Facebook plugin: 'ionic cordova plugin add cordova-plugin-facebook4'
plugin_not_installed
WARN: Ionic Native: tried calling Facebook.login, but the Facebook plugin is not installed.

How should I install and use this specific plugin? Thanks

**Comment by MaximBelov** [comment]
Hi
Follow instructions from 
https://www.npmjs.com/package/cordova-plugin-fbsdk

cordova plugin add cordova-plugin-fbsdk --save --variable APP_ID="123456789" --variable APP_NAME="myApplication" --variable CLIENT_TOKEN="abcd1234"

Regarding warning

```
WARN: Ionic Native: tried calling Facebook.login, but the Facebook plugin is not installed.
```

You have 2 options:
1. Ignore it 
or 
2. Use awesome-cordova-plugins see demo project here https://github.com/MaximBelov/cordova-plugin-fbsdk/blob/master/demo/package.json

```
    "@awesome-cordova-plugins/core": "6.11.0",
    "@awesome-cordova-plugins/facebook": "6.11.0",
```

**Comment by luispimenta** [comment]
@MaximBelov works fine, thanks a lot \o/
