### ISSUE TITLE
ConnectPlugin.java:297: error: cannot find symbol

### ISSUE THREAD

**Issue by betoweef** [MaximBelov/cordova-plugin-fbsdk#3]
Hi.

I've been getting this error when trying to build for android platform.
![Screen Shot 2022-11-08 at 18 01 38](https://user-images.githubusercontent.com/106984727/200674761-5805480d-0ee2-4dc3-99d3-ce577d46ec7d.png)

don't know exactly what's happening

maybe I'm missing something?

Thank you in advance for your help

**Comment by MaximBelov** [comment]
Check config.xml

`  <platform name="android">

      <preference name="android-minSdkVersion" value="22" /> 

      <preference name="android-targetSdkVersion" value="32" />

      <preference name="android-compileSdkVersion" value="32" />

...
  </platform>
`
